# TITLE
## Hotels Price Analysis - Using OYO

### INTRODUCTION
#### OYO is a hotel management and booking company that aims to provide affordable and standardized accommodation options to travelers. OYO Rooms , also known as OYO Hotels & Homes, is an Indian multinational hospitality chain of leased and franchised hotels, homes, and living spaces.

### Problem statement:

* Price analysis based on features like wifi, elevator,tv etc..
* Price analysis based on votes and ratings 
* Based on the location 
* Rating category distribution
* Display the most papular hotels over the city
* Correlation

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import re

### Hyderabad

In [3]:
names=[]
address=[]
city=[]
features=[]
ratings=[]
votes=[]
remarks=[]
prices=[]
distance=[]

for i in range(1,6):
    url="https://www.oyorooms.com/hotels-in-hyderabad/?page="+str(i)
    print(url)

    page=requests.get(url,headers = {'User-Agent':'Mozilla/5.0'})
    soup=BeautifulSoup(page.text)
    
    
    h=soup.find_all("a",class_="c-nn640c u-width100")
    for i in h:
        a=i.text
        names.append(a)
        
    ar=soup.find_all("span",class_="u-line--clamp-2")
    for i in ar:
        a=i.text
        address.append(a.replace(', Hyderabad', ""))
        
    ar=soup.find_all("span",class_="u-line--clamp-2")
    for i in ar:
        a=i.text
        city.append(re.findall(r"Hyderabad",a))
        
    f=soup.find_all("div",class_="amenityWrapper")
    for i in f:
        a=i.text
        features.append(a.split("+")[0])
        
        
    r2=soup.find_all("div",class_="hotelRating")
    for i in r2:
        a=i.text
        ratings.append(a.split()[0])
    
    
    for i in r2:
        a=i.text
        b=re.findall(f"\W(\d+)\sRatings\W",a)
        votes.append(b)
        
    d=soup.find_all("span",class_="listingHotelDescription__distanceText")
    for i in d:
        a=i.text
        distance.append(a)
    

    
    
    p1=soup.find_all("div",class_="listingPrice__numbers")
    for i in p1:
        a=i.text
        prices.append(a.split("â‚¹")[1])

https://www.oyorooms.com/hotels-in-hyderabad/?page=1
https://www.oyorooms.com/hotels-in-hyderabad/?page=2
https://www.oyorooms.com/hotels-in-hyderabad/?page=3
https://www.oyorooms.com/hotels-in-hyderabad/?page=4
https://www.oyorooms.com/hotels-in-hyderabad/?page=5

In [4]:
print(len(names))
print(len(address))
print(len(city))
print(len(features))
print(len(ratings))
print(len(votes))
print(len(prices))
print(len(distance))

100
100
100
100
100
100
100
100

In [5]:
d={"Hotel_Names":names,
    "Distance":distance,
   "Address":address,
   "City":city,
   "Ratings":ratings,
   "Votes":votes,
   "Prices":prices,
   "Features":features
  }

In [6]:
df=pd.DataFrame(d)
df

,Hotel_Names,Distance,Address,City,Ratings,Votes,Prices,Features
0,OYO 14669 Mayur's Residency,2.4 km,"Near Sri Krupa Market, Malakpet",[Hyderabad],4.0,[1015],497,Free Wifi AC AC
1,Flagship 76687 Ramoji Kothapet,5.8 km,Kothapet,[Hyderabad],4.0,[2202],538,Private entrance Reception Free Wifi
2,Capital O 10225 Wild Wings Hotel,6.0 km,"Laxmi Nagar Colony, Kothapet",[Hyderabad],4.0,[818],501,Parking facility Free Wifi Power backup
3,OYO 40869 White Ridge,7.1 km,"Near Sanjeevini Hospital, Kothapet road",[Hyderabad],4.2,[1825],497,Reception Free Wifi Power backup
4,SPOT ON 81775 Mohit Gokul Lodge New Room's,5.9 km,Near To Secunderbad East Metro Rail Station,[Hyderabad],3.5,[675],510,Parking facility Reception Free Wifi
...,...,...,...,...,...,...,...,...
95,Collection O 80304 Hotel Pnr Banjara Hills,6.4 km,Guru Bramaha,[Hyderabad],3.7,[784],1127,Parking facility Elevator Free Wifi
96,OYO 91495 Hotel Vijay Laxmi Residency,9.8 km,Erragadda Metro Station,[],4.0,[575],911,Parking facility Reception Ticket tour assi...
97,Collection O 9386 Hotel Happy Stay,6.9 km,"Near ICICI Bank, Begumpet",[Hyderabad],3.8,[1739],1086,AC TV
98,OYO 71210 Jubilee Homes,8.1 km,"Centrally Located, Near Annapurna Studios, Jub...",[Hyderabad],3.9,[472],862,Parking facility Reception Free Wifi
99,OYO 61506 Sai Residency,8.7 km,"Near Sr nagar metro station, Jawahar Nagar",[Hyderabad],3.5,[605],811,Reception Free Wifi Geyser

### Bangalore

In [7]:
names=[]
address=[]
city=[]
features=[]
ratings=[]
votes=[]
remarks=[]
prices=[]
distance=[]

for i in range(1,6):

    url="https://www.oyorooms.com/hotels-in-bangalore/?page="+str(i)

    print(url)

    page=requests.get(url,headers = {'User-Agent':'Mozilla/5.0'})
    soup=BeautifulSoup(page.text)
    
    
    h=soup.find_all("a",class_="c-nn640c u-width100")
    for i in h:
        a=i.text
        names.append(a)
        
    ar=soup.find_all("span",class_="u-line--clamp-2")
    for i in ar:
        a=i.text
        address.append(a.replace(', Bangalore', ""))
        
    ar=soup.find_all("span",class_="u-line--clamp-2")
    for i in ar:
        a=i.text
        city.append(re.findall(r"Bangalore",a))
        
    f=soup.find_all("div",class_="amenityWrapper")
    for i in f:
        a=i.text
        features.append(a.split("+")[0])
   
        
        
    r2=soup.find_all("div",class_="hotelRating")
    for i in r2:
        a=i.text
        ratings.append(a.split()[0])
    
    
    for i in r2:
        a=i.text
        b=re.findall(f"\W(\d+)\sRatings\W",a)
        votes.append(b)
        
    d=soup.find_all("span",class_="listingHotelDescription__distanceText")
    for i in d:
        a=i.text
        distance.append(a)
    

    
    
    p1=soup.find_all("div",class_="listingPrice__numbers")
    for i in p1:
        a=i.text
        prices.append(a.split("â‚¹")[1])

https://www.oyorooms.com/hotels-in-bangalore/?page=1
https://www.oyorooms.com/hotels-in-bangalore/?page=2
https://www.oyorooms.com/hotels-in-bangalore/?page=3
https://www.oyorooms.com/hotels-in-bangalore/?page=4
https://www.oyorooms.com/hotels-in-bangalore/?page=5

In [19]:
print(len(names))
print(len(address))
print(len(city))
print(len(features))
print(len(ratings))
print(len(votes))
print(len(prices))
print(len(distance))

100
100
100
100
100
100
100
100

In [10]:
features.insert(95,np.NaN)
features.insert(98,np.NaN)

In [8]:
d={"Hotel_Names":names,
    "Distance":distance,
   "Address":address,
   "City":city,
   "Ratings":ratings,
   "Votes":votes,
   "Prices":prices,
   "Features":features
  }

In [11]:
df2=pd.DataFrame(d)
df2

,Hotel_Names,Distance,Address,City,Ratings,Votes,Prices,Features
0,OYO 15358 Hotel Townhall,1.6 km,"Near Dhanlakshmi Bank, JC Road",[Bangalore],4.1,[1247],505,Elevator Parking facility Free Wifi
1,OYO 62331 Gn Collection O,6.3 km,"Centrally Located, Near A D Halli Park, Housin...",[Bangalore],3.9,[693],531,Reception Free Wifi Power backup
2,OYO 3664 Hotel Shivaals Residency,5.1 km,Rajajinagar,[Bangalore],3.8,[202],497,Doctor on call Parking facility Reception
3,SPOT ON 41554 Hotel Sri Thirumala Paradise,2.8 km,Sevashrama,[Bangalore],4.6,[3632],718,Free Wifi CCTV cameras Power backup
4,SPOT ON 48822 Balaji Residency,6.9 km,L N Colony,[Bangalore],3.6,[606],400,AC TV Queen Sized Bed
...,...,...,...,...,...,...,...,...
95,OYO Home 81332 Shiva Shakthi Inn,7.8 km,J P Nagar,[Bangalore],3.9,[1405],906,NaN
96,Collection O 81407 Home Comforts,6.7 km,Bangalore Urban,"[Bangalore, Bangalore]",4.2,[644],2089,Parking facility Free Wifi Power backup
97,Capital O 14273 Inn@silicon Valley,6.8 km,"Service Road, Koramangala, Bengaluru",[],3.9,[842],1464,Parking facility Cot Free Wifi
98,OYO 13121 Sai Kuteer,8.2 km,"Near MG school, Bilekahalli",[Bangalore],3.5,[161],641,NaN
99,OYO 87519 Nra Residency,9.1 km,Rajarajeshwari Nagar,[Bangalore],3.5,[351],819,Parking facility Reception Free Wifi

### Delhi

In [12]:
names=[]
address=[]
city=[]
features=[]
ratings=[]
votes=[]
remarks=[]
prices=[]
distance=[]
for i in range(1,6):
    url="https://www.oyorooms.com/hotels-in-delhi/?page="+str(i)
    page=requests.get(url,headers = {'User-Agent':'Mozilla/5.0'})
    soup=BeautifulSoup(page.text)
    print(url)
    
    
    h=soup.find_all("a",class_="c-nn640c u-width100")
    for i in h:
        a=i.text
        names.append(a)
        
    ar=soup.find_all("span",class_="u-line--clamp-2")
    for i in ar:
        a=i.text
        address.append(a.replace(', Delhi', ""))
        
    ar=soup.find_all("span",class_="u-line--clamp-2")
    for i in ar:
        a=i.text
        city.append(re.findall(r"Delhi",a))
        
    f=soup.find_all("div",class_="amenityWrapper")
    for i in f:
        a=i.text
        features.append(a.split("+")[0])
        
        
    r2=soup.find_all("div",class_="hotelRating")
    for i in r2:
        a=i.text
        ratings.append(a.split()[0])
    
    
    for i in r2:
        a=i.text
        b=re.findall(f"\W(\d+)\sRatings\W",a)
        votes.append(b)
        
    d=soup.find_all("span",class_="listingHotelDescription__distanceText")

    for i in d:
        a=i.text
        distance.append(a)    
   
    
    
    p1=soup.find_all("div",class_="listingPrice__numbers")
    for i in p1:
        a=i.text
        prices.append(a.split("â‚¹")[1])

https://www.oyorooms.com/hotels-in-delhi/?page=1
https://www.oyorooms.com/hotels-in-delhi/?page=2
https://www.oyorooms.com/hotels-in-delhi/?page=3
https://www.oyorooms.com/hotels-in-delhi/?page=4
https://www.oyorooms.com/hotels-in-delhi/?page=5

In [13]:
print(len(names))
print(len(address))
print(len(city))
print(len(features))
print(len(ratings))
print(len(votes))
print(len(prices))
print(len(distance))

100
100
100
99
100
100
100
100

In [14]:
features.insert(97,np.nan)

In [15]:
d={"Hotel_Names":names,
    "Distance":distance,
   "Address":address,
   "City":city,
   "Ratings":ratings,
   "Votes":votes,
   "Prices":prices,
   "Features":features
  }

In [16]:
df3=pd.DataFrame(d)
df3

,Hotel_Names,Distance,Address,City,Ratings,Votes,Prices,Features
0,Collection O 77161 Shalimar Bagh,7.5 km,Shalimar Village,[Delhi],4.0,[2768],531,Free Wifi AC TV
1,SPOT ON 40016 Hotel Vandana,4.6 km,Near New Delhi Railway Station,"[Delhi, Delhi]",3.9,[687],474,AC Parking facility Free Wifi
2,OYO Townhouse 610 Derawal Nagar,3.4 km,"Near Vinayak Hoptiat, Gujranwala Town",[Delhi],5.0,[2849],2391,Private entrance Reception Free Wifi
3,OYO 81741 Hotel Naseeb,4.7 km,Paharganj,[Delhi],3.9,[6],626,Doctor on call Hair Dryer Reception
4,OYO 15515 Hotel Landmark Inn,5.1 km,Near Karol Bagh Metro Station,[],4.7,[4242],1144,Hair Dryer Free Wifi Power backup
...,...,...,...,...,...,...,...,...
95,OYO Flagship 805338 GREEN HOMES,8.1 km,Block D,[Delhi],NEW,[],564,Geyser Power backup AC
96,OYO Flagship 804688 Deva Guest House,7.8 km,ganga enclave delhi,[Delhi],2.5,[27],626,Geyser Power backup AC
97,OYO Townhouse 670 Hotel 16,6.1 km,Adarsh Nagar,[Delhi],2.7,[92],673,NaN
98,Townhouse 750 Billa's Jyot,5.1 km,Near RK Ashram Metro Station,[Delhi],3.6,[492],758,Free Wifi AC AC
99,OYO Flagsip81100 Hotel Vintage Inn,5.0 km,New Delhi,"[Delhi, Delhi]",3.5,[387],1199,Reception Ticket tour assistance Caretaker

### Kolkata

In [17]:
names=[]
address=[]
city=[]
features=[]
ratings=[]
votes=[]
remarks=[]
prices=[]
distance=[]
for i in range(1,6):
    url="https://www.oyorooms.com/hotels-in-kolkata/?page="+str(i)
    page=requests.get(url,headers = {'User-Agent':'Mozilla/5.0'})
    soup=BeautifulSoup(page.text)
    print(url)
    
    
    h=soup.find_all("a",class_="c-nn640c u-width100")
    for i in h:
        a=i.text
        names.append(a)
        
    ar=soup.find_all("span",class_="u-line--clamp-2")
    for i in ar:
        a=i.text
        address.append(a.replace(', Kolkata', ""))
        
    ar=soup.find_all("span",class_="u-line--clamp-2")
    for i in ar:
        a=i.text
        city.append(re.findall(r"Kolkata",a))
        
    f=soup.find_all("div",class_="amenityWrapper")
    for i in f:
        a=i.text
        features.append(a.split("+")[0])
        
        
    r2=soup.find_all("div",class_="hotelRating")
    for i in r2:
        a=i.text
        ratings.append(a.split()[0])
    
    
    for i in r2:
        a=i.text
        b=re.findall(f"\W(\d+)\sRatings\W",a)
        votes.append(b)
        
    d=soup.find_all("span",class_="listingHotelDescription__distanceText")

    for i in d:
        a=i.text
        distance.append(a)    
   
    
    
    p1=soup.find_all("div",class_="listingPrice__numbers")
    for i in p1:
        a=i.text
        prices.append(a.split("â‚¹")[1])

https://www.oyorooms.com/hotels-in-kolkata/?page=1
https://www.oyorooms.com/hotels-in-kolkata/?page=2
https://www.oyorooms.com/hotels-in-kolkata/?page=3
https://www.oyorooms.com/hotels-in-kolkata/?page=4
https://www.oyorooms.com/hotels-in-kolkata/?page=5

In [18]:
print(len(names))
print(len(address))
print(len(city))
print(len(features))
print(len(ratings))
print(len(votes))
print(len(prices))
print(len(distance))

100
100
100
98
100
100
100
100

In [19]:
features.insert(94,np.nan)
features.insert(98,np.nan)

In [20]:
d={"Hotel_Names":names,
    "Distance":distance,
   "Address":address,
   "City":city,
   "Ratings":ratings,
   "Votes":votes,
   "Prices":prices,
   "Features":features
  }

In [21]:
df4=pd.DataFrame(d)
df4

,Hotel_Names,Distance,Address,City,Ratings,Votes,Prices,Features
0,OYO 1764 Hotel Maruti Lodging,8.8 km,"Above Reliance Trends, Raghunathpur",[Kolkata],4.0,[348],501,Parking facility Elevator Free Wifi
1,OYO 46115 Kuber Residency,6.6 km,"Near Tagore Park, Kasba",[Kolkata],3.9,[1404],623,Reception Free Wifi Power backup
2,Collection O 7741 Hotel Hamza International,0.6 km,"Near College Street, MG Road",[Kolkata],4.3,[1823],1299,Parking facility Reception Free Wifi
3,SPOT ON 64196 Silver Green,9.8 km,"Mondal Ganthi Road, Kaikhali, VIP Road Kolkata...",[Kolkata],4.7,[3042],731,TV Parking facility Reception
4,Collection O 76820 The Kolkata Hotel,7.4 km,Kasbah North,[Kolkata],4.5,[1488],974,Free Wifi Power backup Security
...,...,...,...,...,...,...,...,...
95,OYO 2872 Hotel City Of Joy,6.2 km,Salt Lake,[Kolkata],4.1,[570],966,Geyser Power backup AC
96,OYO Flagship 804578 99 Kombo Stay,9.4 km,Kolkata Airport Haldiram,"[Kolkata, Kolkata]",3.6,[27],626,Reception Free Wifi Power backup
97,Flagship 37100 Apan Guest House,9.9 km,Near Mukundapur Bus Stop R.N Tagore Institute...,[Kolkata],3.6,[191],687,Free Wifi Geyser CCTV cameras
98,Collection O 78897 Collection O Ketan Regency,8.4 km,953 Purbachal Road adapt House Prince Park Kal...,[],4.3,[1687],1684,NaN
99,OYO Flagship 85986 Two Inn,6.8 km,block I Kolkata-700039 Near prince saloon,"[Kolkata, Kolkata]",3.8,[106],687,Reception Free Wifi Power backup

In [22]:
df5=pd.concat([df,df2],axis=0)
df6=pd.concat([df3,df4],axis=0)

In [23]:
final=pd.concat([df5,df6],axis=0)

In [24]:
final=final.reset_index()

In [25]:
final.drop('index',axis=1,inplace=True)

In [26]:
final

,Hotel_Names,Distance,Address,City,Ratings,Votes,Prices,Features
0,OYO 14669 Mayur's Residency,2.4 km,"Near Sri Krupa Market, Malakpet",[Hyderabad],4.0,[1015],497,Free Wifi AC AC
1,Flagship 76687 Ramoji Kothapet,5.8 km,Kothapet,[Hyderabad],4.0,[2202],538,Private entrance Reception Free Wifi
2,Capital O 10225 Wild Wings Hotel,6.0 km,"Laxmi Nagar Colony, Kothapet",[Hyderabad],4.0,[818],501,Parking facility Free Wifi Power backup
3,OYO 40869 White Ridge,7.1 km,"Near Sanjeevini Hospital, Kothapet road",[Hyderabad],4.2,[1825],497,Reception Free Wifi Power backup
4,SPOT ON 81775 Mohit Gokul Lodge New Room's,5.9 km,Near To Secunderbad East Metro Rail Station,[Hyderabad],3.5,[675],510,Parking facility Reception Free Wifi
...,...,...,...,...,...,...,...,...
395,OYO 2872 Hotel City Of Joy,6.2 km,Salt Lake,[Kolkata],4.1,[570],966,Geyser Power backup AC
396,OYO Flagship 804578 99 Kombo Stay,9.4 km,Kolkata Airport Haldiram,"[Kolkata, Kolkata]",3.6,[27],626,Reception Free Wifi Power backup
397,Flagship 37100 Apan Guest House,9.9 km,Near Mukundapur Bus Stop R.N Tagore Institute...,[Kolkata],3.6,[191],687,Free Wifi Geyser CCTV cameras
398,Collection O 78897 Collection O Ketan Regency,8.4 km,953 Purbachal Road adapt House Prince Park Kal...,[],4.3,[1687],1684,NaN
399,OYO Flagship 85986 Two Inn,6.8 km,block I Kolkata-700039 Near prince saloon,"[Kolkata, Kolkata]",3.8,[106],687,Reception Free Wifi Power backup

In [42]:
final.to_csv("raw_data_oyo_rooms.csv")

### CLEANING

### cleaning city

#### Hyderabad

In [27]:
l=[]
for i in df['City']:
    a=str(i).strip("[]")
    l.append(a)
df['City']=l

In [28]:
df['City'].value_counts()

'Hyderabad'                 91
'Hyderabad', 'Hyderabad'     6
                             3
Name: City, dtype: int64

In [29]:
df['City']=df['City'].apply(lambda x:x.replace("'",""))
df['City']=df['City'].apply(lambda x:x.replace(", Hyderabad",""))

In [30]:
df['City'].value_counts()

Hyderabad    97
              3
Name: City, dtype: int64

In [31]:
df = df.replace(r'^\s*$', 'Hyderabad', regex=True)

In [32]:
df['City'].value_counts()

Hyderabad    100
Name: City, dtype: int64

### Bangalore

In [33]:
l=[]
for i in df2['City']:
    a=str(i).strip("[]")
    l.append(a)
df2['City']=l

In [34]:
df2['City'].value_counts()

'Bangalore'                 85
'Bangalore', 'Bangalore'     8
                             7
Name: City, dtype: int64

In [35]:
df2['City']=df2['City'].apply(lambda x:x.replace("'",""))
df2['City']=df2['City'].apply(lambda x:x.replace(", Bangalore",""))

In [36]:
df2['City'].value_counts()

Bangalore    93
              7
Name: City, dtype: int64

In [37]:
df2 = df2.replace(r'^\s*$', 'Bangalore', regex=True)

In [38]:
df2['City'].value_counts()

Bangalore    100
Name: City, dtype: int64

### Delhi

In [39]:
l=[]
for i in df3['City']:
    a=str(i).strip("[]")
    l.append(a)
df3['City']=l

In [40]:
df3['City'].value_counts()

'Delhi'             74
'Delhi', 'Delhi'    20
                     6
Name: City, dtype: int64

In [41]:
df3['City']=df3['City'].apply(lambda x:x.replace("'",""))
df3['City']=df3['City'].apply(lambda x:x.replace(", Delhi",""))

In [42]:
df3['City'].value_counts()

Delhi    94
          6
Name: City, dtype: int64

In [43]:
df3 = df3.replace(r'^\s*$', 'Delhi', regex=True)

In [44]:
df3['City'].value_counts()

Delhi    100
Name: City, dtype: int64

### Kolkata

In [45]:
l=[]
for i in df4['City']:
    a=str(i).strip("[]")
    l.append(a)
df4['City']=l

In [46]:
df4['City'].value_counts()

'Kolkata'                          87
                                    6
'Kolkata', 'Kolkata'                6
'Kolkata', 'Kolkata', 'Kolkata'     1
Name: City, dtype: int64

In [47]:
df4['City']=df4['City'].apply(lambda x:x.replace("'",""))
df4['City']=df4['City'].apply(lambda x:x.replace(", Kolkata",""))

In [48]:
df4['City'].value_counts()

Kolkata    94
            6
Name: City, dtype: int64

In [49]:
df4 = df4.replace(r'^\s*$', 'Kolkata', regex=True)

In [50]:
df4['City'].value_counts()

Kolkata    100
Name: City, dtype: int64

In [51]:
df5=pd.concat([df,df2],axis=0)
df6=pd.concat([df3,df4],axis=0)

In [52]:
final=pd.concat([df5,df6],axis=0)

In [53]:
final=final.reset_index()
final.drop('index',axis=1,inplace=True)

### Distance

### we are removing kms in Distance

In [54]:
final['Distance']=final['Distance'].str.replace("km","")

In [55]:
final.head(10)

,Hotel_Names,Distance,Address,City,Ratings,Votes,Prices,Features
0,OYO 14669 Mayur's Residency,2.4,"Near Sri Krupa Market, Malakpet",Hyderabad,4.0,[1015],497,Free Wifi AC AC
1,Flagship 76687 Ramoji Kothapet,5.8,Kothapet,Hyderabad,4.0,[2202],538,Private entrance Reception Free Wifi
2,Capital O 10225 Wild Wings Hotel,6.0,"Laxmi Nagar Colony, Kothapet",Hyderabad,4.0,[818],501,Parking facility Free Wifi Power backup
3,OYO 40869 White Ridge,7.1,"Near Sanjeevini Hospital, Kothapet road",Hyderabad,4.2,[1825],497,Reception Free Wifi Power backup
4,SPOT ON 81775 Mohit Gokul Lodge New Room's,5.9,Near To Secunderbad East Metro Rail Station,Hyderabad,3.5,[675],510,Parking facility Reception Free Wifi
5,OYO 70927 Hotel Hyderabad Continental,0.7,"Near Tarakarama Theatre, Sultan Bazar",Hyderabad,3.8,[1526],621,TV King Sized Bed Dress Hanger
6,OYO 19365 Hotel Sabharwal,0.9,"Near Grand Hotel , Hanuman Tekdi",Hyderabad,3.3,[425],598,Elevator Free Wifi Geyser
7,SPOT ON 37214 Classic Lodge,1.9,Near Board Of Intermediate Office,Hyderabad,4.0,[1448],520,AC Parking facility Elevator
8,SPOT ON 72246 Gayatri Lodge,5.4,Ranigunj,Hyderabad,4.0,[632],447,Reception Free Wifi Power backup
9,OYO Flagship 80484 Simra Relax Inn,4.1,Hyderabad,Hyderabad,4.2,[58],702,Geyser Power backup AC

### Votes

In [56]:
l=[]
for i in final['Votes']:
    a=str(i).strip("['']")
    l.append(a)
final['Votes']=l

In [57]:
final =final.replace(r'^\s*$', 'NEW', regex=True)

In [58]:
final['Votes']=final['Votes'].replace('NEW',876)

### Ratings

In [59]:
final['Ratings'].value_counts()

4.0    38
4.2    33
4.3    30
3.7    29
3.9    29
3.6    26
3.8    23
3.5    23
4.1    19
4.4    17
3.4    17
4.5    13
3.3    13
3.2    10
4.7    10
4.6     8
NEW     8
3.1     7
5.0     7
2.7     7
4.8     5
2.9     5
2.5     3
4.9     3
2.8     2
1.9     2
3.0     2
2.3     2
1.7     2
2.4     2
2.0     1
1.8     1
2.6     1
1.0     1
2.1     1
Name: Ratings, dtype: int64

In [60]:
final['Ratings']=final['Ratings'].replace("NEW",0)

In [61]:
final['Ratings'].value_counts()

4.0    38
4.2    33
4.3    30
3.7    29
3.9    29
3.6    26
3.8    23
3.5    23
4.1    19
4.4    17
3.4    17
4.5    13
3.3    13
3.2    10
4.7    10
4.6     8
0       8
3.1     7
5.0     7
2.7     7
4.8     5
2.9     5
2.5     3
4.9     3
2.8     2
1.9     2
3.0     2
2.3     2
1.7     2
2.4     2
2.0     1
1.8     1
2.6     1
1.0     1
2.1     1
Name: Ratings, dtype: int64

### Checking NaN values

In [62]:
final.isna().sum()

Hotel_Names    0
Distance       0
Address        0
City           0
Ratings        0
Votes          0
Prices         0
Features       5
dtype: int64

### In features column we are filling the NaN values with ffill

In [63]:
final['Features'].fillna(method='ffill',inplace=True)

In [64]:
final.isna().sum()

Hotel_Names    0
Distance       0
Address        0
City           0
Ratings        0
Votes          0
Prices         0
Features       0
dtype: int64

In [65]:
final

,Hotel_Names,Distance,Address,City,Ratings,Votes,Prices,Features
0,OYO 14669 Mayur's Residency,2.4,"Near Sri Krupa Market, Malakpet",Hyderabad,4.0,1015,497,Free Wifi AC AC
1,Flagship 76687 Ramoji Kothapet,5.8,Kothapet,Hyderabad,4.0,2202,538,Private entrance Reception Free Wifi
2,Capital O 10225 Wild Wings Hotel,6.0,"Laxmi Nagar Colony, Kothapet",Hyderabad,4.0,818,501,Parking facility Free Wifi Power backup
3,OYO 40869 White Ridge,7.1,"Near Sanjeevini Hospital, Kothapet road",Hyderabad,4.2,1825,497,Reception Free Wifi Power backup
4,SPOT ON 81775 Mohit Gokul Lodge New Room's,5.9,Near To Secunderbad East Metro Rail Station,Hyderabad,3.5,675,510,Parking facility Reception Free Wifi
...,...,...,...,...,...,...,...,...
395,OYO 2872 Hotel City Of Joy,6.2,Salt Lake,Kolkata,4.1,570,966,Geyser Power backup AC
396,OYO Flagship 804578 99 Kombo Stay,9.4,Kolkata Airport Haldiram,Kolkata,3.6,27,626,Reception Free Wifi Power backup
397,Flagship 37100 Apan Guest House,9.9,Near Mukundapur Bus Stop R.N Tagore Institute...,Kolkata,3.6,191,687,Free Wifi Geyser CCTV cameras
398,Collection O 78897 Collection O Ketan Regency,8.4,953 Purbachal Road adapt House Prince Park Kal...,Kolkata,4.3,1687,1684,Free Wifi Geyser CCTV cameras
399,OYO Flagship 85986 Two Inn,6.8,block I Kolkata-700039 Near prince saloon,Kolkata,3.8,106,687,Reception Free Wifi Power backup

### we are changing the data types

In [66]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Hotel_Names  400 non-null    object
 1   Distance     400 non-null    object
 2   Address      400 non-null    object
 3   City         400 non-null    object
 4   Ratings      400 non-null    object
 5   Votes        400 non-null    object
 6   Prices       400 non-null    object
 7   Features     400 non-null    object
dtypes: object(8)
memory usage: 25.1+ KB

In [67]:
final['Distance']=final['Distance'].astype("float")
final['Ratings']=final['Ratings'].astype("float")
final['Prices']=final['Prices'].astype("float")
final['Votes']=final['Votes'].astype("int")

In [68]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Hotel_Names  400 non-null    object
 1   Distance     400 non-null    float64
 2   Address      400 non-null    object
 3   City         400 non-null    object
 4   Ratings      400 non-null    float64
 5   Votes        400 non-null    int32
 6   Prices       400 non-null    float64
 7   Features     400 non-null    object
dtypes: float64(3), int32(1), object(4)
memory usage: 23.6+ KB

In [104]:
final.to_csv("Hotels_Price_Analysis.csv")

In [69]:
final

,Hotel_Names,Distance,Address,City,Ratings,Votes,Prices,Features
0,OYO 14669 Mayur's Residency,2.4,"Near Sri Krupa Market, Malakpet",Hyderabad,4.0,1015,497.0,Free Wifi AC AC
1,Flagship 76687 Ramoji Kothapet,5.8,Kothapet,Hyderabad,4.0,2202,538.0,Private entrance Reception Free Wifi
2,Capital O 10225 Wild Wings Hotel,6.0,"Laxmi Nagar Colony, Kothapet",Hyderabad,4.0,818,501.0,Parking facility Free Wifi Power backup
3,OYO 40869 White Ridge,7.1,"Near Sanjeevini Hospital, Kothapet road",Hyderabad,4.2,1825,497.0,Reception Free Wifi Power backup
4,SPOT ON 81775 Mohit Gokul Lodge New Room's,5.9,Near To Secunderbad East Metro Rail Station,Hyderabad,3.5,675,510.0,Parking facility Reception Free Wifi
...,...,...,...,...,...,...,...,...
395,OYO 2872 Hotel City Of Joy,6.2,Salt Lake,Kolkata,4.1,570,966.0,Geyser Power backup AC
396,OYO Flagship 804578 99 Kombo Stay,9.4,Kolkata Airport Haldiram,Kolkata,3.6,27,626.0,Reception Free Wifi Power backup
397,Flagship 37100 Apan Guest House,9.9,Near Mukundapur Bus Stop R.N Tagore Institute...,Kolkata,3.6,191,687.0,Free Wifi Geyser CCTV cameras
398,Collection O 78897 Collection O Ketan Regency,8.4,953 Purbachal Road adapt House Prince Park Kal...,Kolkata,4.3,1687,1684.0,Free Wifi Geyser CCTV cameras
399,OYO Flagship 85986 Two Inn,6.8,block I Kolkata-700039 Near prince saloon,Kolkata,3.8,106,687.0,Reception Free Wifi Power backup